### ISSUE TITLE
version problem

### ISSUE THREAD

**Issue by 12num** [InhwanBae/GPGraph#1]
What are the versions of cuda and pytorch you are using, and I did not find your requirements.tx. Thank you very much if you can share it！

**Comment by InhwanBae** [comment]
Hi @12num!

Thanks for your interest in my work! I did all experiments on the RTX 3090 system(Ubuntu 20.04, PyTorch 1.9.0, CUDA 11.1). However, I checked that this code works well in various versions of PyTorch(1.7, 1.8, 1.9), CUDA(10, 11) and GPU(2080ti, 3090).

**Comment by 12num** [comment]
Thank you very much for your reply, very useful. Thanks again for sharing your work publicly.
