### ISSUE TITLE
Trajectory visualization

### ISSUE THREAD

**Issue by caaaadac** [InhwanBae/GPGraph#3]
Hello, may I ask how the pedestrian trajectory visualization in the paper is realized?
![image](https://user-images.githubusercontent.com/112396864/188088958-3b537528-a321-4e39-b505-569429934b50.png)
![image](https://user-images.githubusercontent.com/112396864/188089240-ea2e3e4f-b9f8-4497-9ba2-ce1192db7d2d.png)

**Comment by InhwanBae** [comment]
Hi @caaaadac!

Basically, I use Matplotlib Plot to visualize the path. For better visualization, I additionally use OpenCV VideoCapture to obtain still images and convert the generated trajectories from a meter coordinate system to an image coordinate system via a homography matrix. This conversion allows the trajectory points to be drawn in the correct head positions of pedestrians on the image.

**Comment by InhwanBae** [comment]
I'm closing this issue for now. Please feel free to open another issue for other questions.

**Comment by haomengz** [comment]
Hi @InhwanBae, thanks for the nice work! Would you mind sharing your visualization code? I am interested in reproducing the visualization.
